#!/bin/bash
# Start HTTP server to serve files for RunPod download
# This avoids scp/rsync connection issues

PROJECT_DIR="/Users/jba7790/Desktop/1UP_2"
PORT=8888

cd "$PROJECT_DIR"

echo "🚀 Iniciando servidor HTTP en puerto $PORT..."
echo "📁 Sirviendo archivos desde: $PROJECT_DIR"
echo ""
echo "En RunPod, ejecuta estos comandos:"
echo ""
echo "cd ~/1UP_2"
echo "python3 << 'ENDPYTHON'"
echo "import urllib.request"
echo "import os"
echo ""
echo "# Tu IP local (reemplaza con tu IP):"
echo "MAC_IP = 'TU_IP_AQUI'  # Ejemplo: '192.168.1.100'"
echo "PORT = $PORT"
echo ""
echo "files = ["
echo "    ('detector.py', 'detector.py'),"
echo "    ('analyzer.py', 'analyzer.py'),"
echo "    ('filters.py', 'filters.py'),"
echo "    ('image_quality.py', 'image_quality.py'),"
echo "    ('camera_utils.py', 'camera_utils.py'),"
echo "    ('storage_v2.py', 'storage_v2.py'),"
echo "    ('storage.py', 'storage.py'),"
echo "    ('server/api.py', 'server/api.py'),"
echo "    ('client/capture_client.py', 'client/capture_client.py'),"
echo "]"
echo ""
echo "for remote_path, local_file in files:"
echo "    url = f'http://{MAC_IP}:{PORT}/{local_file}'"
echo "    print(f'📥 Descargando {local_file}...')"
echo "    urllib.request.urlretrieve(url, remote_path)"
echo "    print(f'✅ {local_file} descargado')"
echo ""
echo "print('✅ Todos los archivos descargados!')"
echo "ENDPYTHON"
echo ""
echo ""
echo "⚠️  IMPORTANTE: Reemplaza 'TU_IP_AQUI' con tu IP local"
echo "   Para obtener tu IP: ifconfig | grep 'inet ' | grep -v 127.0.0.1"
echo ""
echo "Presiona Ctrl+C para detener el servidor"
echo ""

python3 -m http.server $PORT
