#!/bin/bash
# Upload files to RunPod via HTTP server
# This avoids scp/rsync connection issues

PROJECT_DIR="/Users/jba7790/Desktop/1UP_2"
PORT=8888
MAC_IP="192.168.1.153"

cd "$PROJECT_DIR"

echo "🚀 =========================================="
echo "🚀 Subir archivos a RunPod vía HTTP"
echo "🚀 =========================================="
echo ""
echo "📋 PASO 1: Iniciar servidor HTTP"
echo "   Ejecuta esto en otra terminal:"
echo "   cd $PROJECT_DIR"
echo "   python3 -m http.server $PORT"
echo ""
echo "📋 PASO 2: En RunPod, ejecuta estos comandos:"
echo ""
echo "cd ~/1UP_2"
echo "python3 << 'ENDPYTHON'"
echo "import urllib.request"
echo "import os"
echo "from pathlib import Path"
echo ""
echo "MAC_IP = '$MAC_IP'"
echo "PORT = $PORT"
echo ""
echo "files = ["
echo "    ('detector.py', 'detector.py'),"
echo "    ('analyzer.py', 'analyzer.py'),"
echo "    ('filters.py', 'filters.py'),"
echo "    ('image_quality.py', 'image_quality.py'),"
echo "    ('camera_utils.py', 'camera_utils.py'),"
echo "    ('storage_v2.py', 'storage_v2.py'),"
echo "    ('storage.py', 'storage.py'),"
echo "    ('server/api.py', 'server/api.py'),"
echo "    ('client/capture_client.py', 'client/capture_client.py'),"
echo "]"
echo ""
echo "for remote_path, local_file in files:"
echo "    url = f'http://{MAC_IP}:{PORT}/{local_file}'"
echo "    print(f'📥 Descargando {local_file}...')"
echo "    try:"
echo "        Path(remote_path).parent.mkdir(parents=True, exist_ok=True)"
echo "        urllib.request.urlretrieve(url, remote_path)"
echo "        print(f'✅ {local_file} descargado')"
echo "    except Exception as e:"
echo "        print(f'❌ Error descargando {local_file}: {e}')"
echo ""
echo "print('✅ Proceso completado!')"
echo "ENDPYTHON"
echo ""
echo "📋 PASO 3: Verificar archivos en RunPod:"
echo "   ls -la ~/1UP_2/*.py"
echo "   ls -la ~/1UP_2/server/*.py"
echo "   ls -la ~/1UP_2/client/*.py"
echo ""
